@HotelListing.Api_HostAddress = https://localhost:7233
 
GET {{HotelListing.Api_HostAddress}}/api/countries

###
POST {{HotelListing.Api_HostAddress}}/api/countries
Content-Type: application/json

{
  "name": "Azerbaijan",
  "shortName": "AZ"
}

###

DELETE {{HotelListing.Api_HostAddress}}/api/countries/{{id}}

###
GET {{HotelListing.Api_HostAddress}}/api/countries/{{id}}
 
###


PUT {{HotelListing.Api_HostAddress}}/api/countries/{{id}}
Content-Type: application/json

{
  "id": 1004,
  "name": "England",
  "shortName": "EN"
}

###






GET {{HotelListing.Api_HostAddress}}/api/hotels

###

POST {{HotelListing.Api_HostAddress}}/api/hotels
Content-Type: application/json

{
  "name": "Hamoton",
  "address": "Rogojskiy Val St 10",
  "rating": 4.6,
  "countryId": 1003
}

###
DELETE {{HotelListing.Api_HostAddress}}/api/hotels/{{id}}

###

GET {{HotelListing.Api_HostAddress}}/api/hotels/{{id}}

###

PUT {{HotelListing.Api_HostAddress}}/api/hotels/{{id}}
Content-Type: application/json

{
  "id": 1007,
  "name": "Hampton",
  "address": "Rogojskiy Val St 10",
  "rating": 4.6,
  "countryId": 1003
}

###





@id = 1005
